Create Probex2_1,2,3,4
rtsubaki00/mysite pull request #13
Opened 2020-04-04 06:42 UTC by rtsubaki00

2020-04-04 07:00 UTC, sakamotomitsu commented
問題
http://php.sevendays-study.com/problemex2.html

2020-04-04 07:12 UTC, sakamotomitsu commented
@rtsubaki00 
probex2-3
probex2-4
はOKです！

probex2_1
probex2-2
ですが、csvを読み込んで表示させてみましょう！
2-2については、ファイルの最後に「Thank you」と書き込んでください

csvについては、slackに貼ります！

2020-04-10 13:49 UTC, sakamotomitsu requested changes
レビューしました。
間違いではないんですが、もっと簡単に書くことができます

2020-04-10 13:49 UTC, sakamotomitsu commented on probex2_1.php
> +  }
全体的の考え方はOKです！
ですが、ここのforをもっと簡単に書けます！
予想つきます？

2020-04-10 13:50 UTC, sakamotomitsu requested changes
レビューしました
一点修正お願いします

2020-04-10 13:50 UTC, sakamotomitsu commented on probex2_2.php
> +echo 'Thank you';
Thank youはファイルに直接書き込んでください！

2020-04-11 01:50 UTC, rtsubaki00 commented on probex2_1.php
> +  }
for($line = 0; $line < $cnt; $line++){
    echo $line.'<br>';
  }

このような感じですか？

2020-04-11 01:54 UTC, rtsubaki00 commented on probex2_2.php
> +echo 'Thank you';
プッシュしました！

2020-04-11 02:02 UTC, sakamotomitsu commented on probex2_1.php
> +  }
ヒントはforは使わないです
違うものでループが出来ます
$cntは要らなくなります

2020-04-11 02:03 UTC, sakamotomitsu commented on probex2_2.php
> +echo 'Thank you';
伝え方が悪かったです…
ファイルに直接は、csvファイルの事です

2020-04-11 02:12 UTC, sakamotomitsu requested changes
修正お願いします！

2020-04-11 02:12 UTC, sakamotomitsu commented on testdata.csv
> +Thank you
phpから書き込んでください

2020-04-11 09:29 UTC, sakamotomitsu commented
@rtsubaki00 
probex2_2.phpはOKでした
強いて言うなら、上のリードの処理は消しておいてもいいですよ

あと、プルリクのタイトルや説明、コミットメッセージはもう少し何をしたのかが分かるようにしておいてください！
後々見返した時に悲しくなりますよ・・・・

2020-04-11 11:00 UTC, rtsubaki00 commented
ありがとうございます！

リードとは、foreachのところですか？？

確かに、悲しくなりそうですね笑
コミットメッセージわかりやすいのにします！

probex2_1.phpの別バージョンわからないので、もう少しヒントください！

2020-04-11 11:04 UTC, sakamotomitsu commented
foreachとcsv読み込みの部分です

ループの関数はforの他に何があります？

2020-04-11 13:58 UTC, rtsubaki00 commented
foreachとwhileです！

2020-04-11 14:04 UTC, sakamotomitsu commented
`$cnt = count($line);`
は行の「,」で区切られた数ぶんforでループしてますよね

それと同じことをforeachかwhileですることができます
さぁ、どちらでしょう！

2020-04-12 05:51 UTC, rtsubaki00 commented
foreachですか？？

どちらか考えていたのですが
やはりどうなるかわかりません、、

2020-04-12 06:52 UTC, sakamotomitsu commented
foreachです

foreachがどういう動きをするか理解してますか？

2020-04-12 08:59 UTC, rtsubaki00 commented
配列に入っている要素を一つずつ、繰り返し取り出すものだと思います！

2020-04-12 09:06 UTC, rtsubaki00 commented
最後にforが使われている理由がよくわからないので教えていただきたいです！

2020-04-12 09:22 UTC, sakamotomitsu commented
@rtsubaki00 
> 配列に入っている要素を一つずつ、繰り返し取り出すものだと思います！

ですです。
あってます
取り出すって言うよりか、要素分ループするって言う方が正しいかもしれません

現状は、下記の様になってます。
```php
 $cnt = count($line);
  for($i = 0; $i < $cnt; $i++){
    echo $line[$i].'<br>';
  }
```
$cnt分ループする様になってます。
その考え方って、foreachでもできる気がしませんか？

2020-04-12 09:24 UTC, sakamotomitsu commented
> 最後にforが使われている理由がよくわからないので教えていただきたいです！

これはどういう意味ですか？
指摘されている理由が分からないっていうことですか？

2020-04-12 10:28 UTC, rtsubaki00 commented
なんだかわかった気がします！
`foreach ($value as $i){
echo $i. '<br>';
}`
このような感じですか？

2020-04-12 10:36 UTC, rtsubaki00 commented
こっちの方もわかった気がします！

foreachで行数を調べて
forで1行の要素数を調べているということですか？

foreachでCSVファイルの表示は完結すると思っており、
forの役割が何かわからなかったので質問させていただきました！
質問が悪く申し訳ありません、、

2020-04-12 12:18 UTC, sakamotomitsu commented
そんな感じです！

2020-04-12 12:21 UTC, sakamotomitsu commented
> foreachで行数を調べて  forで1行の要素数を調べているということですか？
foreachでCSVファイルの表示は完結すると思っており、  forの役割が何かわからなかったので質問させていただきました！  質問が悪く申し訳ありません、、

何でそうなるのかが分からない状態で提出はやめてください…
調べてコピペしたなら、なぜそういう構成なのかを調べて（分からなければ聞いてください！）から提出してください！
そうしないとただ単に課題をこなしてるしかなりません…

2020-04-12 13:06 UTC, rtsubaki00 commented
すみませんでした、気を付けます、、


array(1) { [0]=> string(36) "Thank youThank youThank youThank you" }
これが出てきました！

2020-04-12 13:08 UTC, sakamotomitsu commented
それはどこで実行したものですか？

2020-04-12 13:10 UTC, rtsubaki00 commented
foreachの外です

2020-04-12 13:13 UTC, sakamotomitsu commented
foreach前とか、foreachの中とかいろんなんとこで見てみてください
何がどうなっているのかをよく観察してみてください！

2020-04-12 14:15 UTC, rtsubaki00 commented
foreachの中に入れると行ごとに表示され、
forの中に入れると一つの要素ごとに表示されることがわかりました！

2020-04-12 14:17 UTC, sakamotomitsu commented
どんな処理の流れか分かってきましたか？

2020-04-12 14:18 UTC, rtsubaki00 commented
わかってきました！

2020-04-12 14:19 UTC, sakamotomitsu commented
よかったです！
ならforの部分をforeachでリファクタリングしてみてください！
（リファクタリングについて知らなかったら、調べてみてください！）

2020-04-12 14:42 UTC, rtsubaki00 commented
やってみます！

2020-04-13 08:41 UTC, rtsubaki00 commented
やっとできました！

Fix for to foreach probex2_2.phpは名前を間違えたので
下に名前書き替えました、、

2020-04-13 12:23 UTC, sakamotomitsu commented
OKです！

コミットメッセージを間違えた時は、コマンドで直せるので次からやってみてください！

2020-04-13 12:25 UTC, merged