probex3_1.php probex3_2.php
rtsubaki00/mysite pull request #14
Opened 2020-04-14 09:04 UTC by rtsubaki00

2020-04-14 14:20 UTC, sakamotomitsu requested changes
レビューしました！

2020-04-14 14:20 UTC, sakamotomitsu commented on probex3_1.php
> +        echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";
```php
$this -> month
```
これはなんですか？

2020-04-14 14:20 UTC, sakamotomitsu commented on probex3_1.php
> +        echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";
クラスの中では、`echo`ではなく`return`を使います！

この記事を読んでみてください
https://www.sejuku.net/blog/23639

2020-04-14 14:20 UTC, sakamotomitsu commented on probex3_2.php
> +?>
ここは、probex3_1.phpで書いたクラスを使ってやってください！

2020-04-15 08:16 UTC, rtsubaki00 commented on probex3_1.php
> +        echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";
`$this -> month` は、
`インスタンス名  -> プロパティ名` でプロパティにアクセスできると書いてあったので使いました！

2020-04-15 14:32 UTC, sakamotomitsu commented on probex3_1.php
> +        echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";
ここでアクセスする意味はなんですか？

2020-04-16 05:38 UTC, rtsubaki00 commented on probex3_1.php
> +        echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";
クラスでプロパティとメソッドを設定→インスタンスで具体的な数字を入れる
ということが分かったので、`echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";`までで基本の形を作って、それ以降の部分で具体的な数字を読み込まさせました

2020-04-16 06:02 UTC, rtsubaki00 commented on probex3_1.php
> +        echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";
funnction のところミスで、本当は　public function です！

2020-04-16 14:59 UTC, sakamotomitsu commented on probex3_1.php
> +        echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";
考えはわかるのですが、`$this -> month`は何か処理に使ってるんですか？

2020-04-17 23:21 UTC, rtsubaki00 commented on probex3_1.php
> +        echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";
考えたのですがよくわからなかったので、もう一度考え直します！

2020-04-18 09:26 UTC, sakamotomitsu commented on probex3_1.php
> +        echo "５か月後の月は".date("m", strtotime($this -> month. "+5 month"))."月です。";
OKです！
もう少し考えてみてください！
その中で、質問があったら何でも良いので聞いてください！！

2020-04-21 09:20 UTC, sakamotomitsu commented
@rtsubaki00 
考え方ですが、そんな感じです！
近いです！

１つヒントです。
何故functionを使うかです。
理由は、同じ処理を沢山書くより1つ共通する処理を書いてそれを呼び出す方が、
後々メンテナンスがしやすくなります。

そういう理由でfunctionにまとめるのですが、
今はどうなっていますか？
それを意識してみて修正してみてください！

2020-04-22 09:30 UTC, rtsubaki00 commented
メソッドで5か月後の月を表示させて、インスタンスの生成で具体的な日付を入れるのが正解だと思うのですが、どうでしょうか？

2020-04-22 12:35 UTC, sakamotomitsu commented
合ってます！！

2020-04-22 13:41 UTC, rtsubaki00 commented
良かったです！もう少しでできそうです！

2020-04-24 14:36 UTC, sakamotomitsu requested changes
probex3_1.phpだけレビューしてます！
考え方はOKです！
あとは詳細の部分です

2020-04-24 14:36 UTC, sakamotomitsu commented on probex3_1.php
> +     }
ここのfunctionはなんですか？

2020-04-24 14:36 UTC, sakamotomitsu commented on probex3_1.php
> +   $month-> get_name ('2020-04-22');
get_nameに引数を渡してますが、何か意味があるんですか？

2020-04-24 14:36 UTC, sakamotomitsu commented on probex3_1.php
> +   echo $month -> get_name();
12行目で同じことをしてますよ！

2020-04-24 14:37 UTC, sakamotomitsu commented
@rtsubaki00 
「メソッド部分とインスタンス部分を分解＋スコープ演算子」は、今の修正点が完了してからお願いします！

2020-04-26 02:00 UTC, rtsubaki00 commented on probex3_1.php
> +   echo $month -> get_name();
`echo $month -> get_name('2020-04-22')`にできそうな気がするのですが、
あってますか？？

2020-04-26 04:41 UTC, sakamotomitsu commented on probex3_1.php
> +   echo $month -> get_name();
> echo $month -> get_name('2020-04-22')にできそうな気がするのですが

は、下の意味で合ってますか？

14行目を消して、12行目にechoを付ける

2020-04-26 06:02 UTC, rtsubaki00 commented on probex3_1.php
> +   echo $month -> get_name();
そうです！

2020-04-26 06:15 UTC, sakamotomitsu commented on probex3_1.php
> +   echo $month -> get_name();
であれば正解です！

2020-04-26 08:28 UTC, rtsubaki00 commented on probex3_1.php
> +   echo $month -> get_name();
良かったです！

2020-04-26 08:29 UTC, rtsubaki00 commented
少し変更してみました！

2020-04-26 08:58 UTC, sakamotomitsu requested changes
コードが綺麗になりました！
その調子です
あと1つです

2020-04-26 08:58 UTC, sakamotomitsu commented on probex3_1_1.php
> +  echo $month  -> showDate(2020-04-25);
`showDate`に引数を渡しているのは何か意味があるんですか？

2020-04-26 12:42 UTC, rtsubaki00 commented on probex3_1_1.php
> +  echo $month  -> showDate(2020-04-25);
メソッド名を指定するために使いました
なくてもできるのですか？？

2020-04-26 13:54 UTC, sakamotomitsu commented on probex3_1_1.php
> +  echo $month  -> showDate(2020-04-25);
引数って言うのは、どの部分か理解してますか？

2020-04-27 06:24 UTC, rtsubaki00 commented on probex3_1_1.php
> +  echo $month  -> showDate(2020-04-25);
2020-04-25の部分ですか？

2020-04-27 06:28 UTC, sakamotomitsu commented on probex3_1_1.php
> +  echo $month  -> showDate(2020-04-25);
そうです　その部分です
関数showDateは、値を受ける設定にしていないので、
`2020-04-25`を送っても何もなりません
ここまで理解できますか？

2020-04-27 08:17 UTC, rtsubaki00 commented on probex3_1_1.php
> +  echo $month  -> showDate(2020-04-25);
probex3_1.phpの
` public function showDate() {
       return date("m", strtotime("+5 month"));
     }`の部分でshowDateの中に何も入っていないからということですか？？

2020-04-27 08:55 UTC, sakamotomitsu commented on probex3_1_1.php
> +  echo $month  -> showDate(2020-04-25);
ですです。
ここの部分です→`showDate()`

もし、
```php
public function showDate($val) {
    // $valを良い具合に処理。
    return date("m", strtotime("+5 month"));
}
```
であれば、
```php
echo $month  -> showDate('2020-04-25');
```
`showDate`に引数があっても間違いではないです！

2020-04-27 12:57 UTC, rtsubaki00 commented on probex3_1_1.php
> +  echo $month  -> showDate(2020-04-25);
なるほど！理解できました！！

2020-04-27 13:20 UTC, sakamotomitsu requested changes
引数について、もう少し詳しく学習しましょう！

2020-04-27 13:20 UTC, sakamotomitsu commented on probex3_1_1.php
> +  echo  $month  -> showDate (2020-04-25);
空白の間隔が変わっただけですよ…
（）の中身を消しといてください！

2020-04-27 13:29 UTC, rtsubaki00 commented on probex3_1_1.php
> +  echo  $month  -> showDate (2020-04-25);
できてなかったですね…すみません
直しました

2020-04-27 13:35 UTC, rtsubaki00 commented on probex3_1_1.php
> +  echo  $month  -> showDate (2020-04-25);
自動販売機にお金を入れる＋ジュースを選ぶが引数だとすると、返り値はジュースになるような感じで入り口と出口が全然違うので、概念自体が難しいですが、深い理解ができるように頑張ろうと思います！

2020-04-27 14:03 UTC, sakamotomitsu commented on probex3_1_1.php
> +  echo  $month  -> showDate (2020-04-25);
自動販売機の例えはよくしますね
初めて間もないので、理解できないのはしょうがないです
やっていって少しづつ理解していきましょう！

2020-04-27 14:04 UTC, sakamotomitsu commented
@rtsubaki00 
`showDate ()`関数名と()の空白を無くした方が綺麗ですよ！

2020-04-27 23:55 UTC, rtsubaki00 commented
どうでしょうか？

2020-04-28 00:00 UTC, sakamotomitsu commented
okです！
次の問題行きましょう！

2020-04-28 04:46 UTC, rtsubaki00 commented
スコープ演算子のところもできてましたか？

2020-04-28 04:48 UTC, sakamotomitsu commented
OKですよ！

2020-04-28 05:03 UTC, rtsubaki00 commented
了解です！次やります！

2020-04-28 05:56 UTC, merged