Fix
rtsubaki00/mysite pull request #8
Opened 2020-03-27 05:23 UTC by rtsubaki00

2020-03-27 08:57 UTC, sakamotomitsu commented
1つ動かないやつがあります
探してみてください！

2020-04-04 06:58 UTC, sakamotomitsu commented
この回答間違ってますね

下記、問題です。
> 変数aに3を設定して、
> 変数aが3以上なら、「こんにちは」と表示し
> 変数aが１なら「今日は良い天気だね」と表示し、
> 変数aが2なら「今日は寒いね」と表示し、
> 変数aが3なら「今日は湿度が高いね」と表示し、
> それ以外なら「さようなら」と表示しなさい

もう少し考えてみてください！
ヒントは欲しければ教えます

2020-04-04 08:00 UTC, sakamotomitsu commented
@rtsubaki00 
もう一度問題を読んでみましょう！

変数aが1の時は何をしたらいいのか・・・・
みたいに、考えれるパターンを書き出してみてください

2020-04-07 10:30 UTC, sakamotomitsu requested changes
修正ありがとうございます！
レビューしました

2020-04-07 10:30 UTC, sakamotomitsu commented on prob4.php
> +   }
よくよく考えると、ここのifは a == 1 部分のelseになる気がするかも・・・
問題のとらえ方の話になってくるので間違いではないですが
どう思いますか？

2020-04-07 14:18 UTC, rtsubaki00 commented on prob4.php
> +   }
それは思いつかなかったです！
そっちの方がすっきりしていると思うので直しておきます！

2020-04-07 14:36 UTC, sakamotomitsu commented on prob4.php
> +   }
お願いします！
これは問題がややこしかったですね

2020-04-09 08:18 UTC, sakamotomitsu commented
@rtsubaki00 
OKです！

2020-04-09 08:18 UTC, merged